services:
  # 1. FRONTEND (React + Vite + Nginx)
  frontend:
    container_name: mozi_frontend
    build:
      context: ./Frontend     # A mappád neve a képen: Frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "8090:80"             # Böngészőben: http://localhost:8090
    restart: unless-stopped

  # 2. ADATBÁZIS (MySQL)
  db:
    image: mysql:8.4
    container_name: mozi_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: mozipont_beta   # A te adatbázis neved
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppw
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      # EZ A SOR TÖLTI BE AZ SQL FÁJLT A db_init MAPPÁBÓL:
      - ./db_init:/docker-entrypoint-initdb.d:ro 

  # 3. PHPMYADMIN (Adatbázis kezelő)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mozi_phpmyadmin
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8082:80"             # Böngészőben: http://localhost:8082

  # 4. BACKEND API (Node.js)
  api:
    build:
      context: ./backend      # A mappád neve a képen: backend
      dockerfile: Dockerfile
    container_name: mozi_api
    restart: unless-stopped
    depends_on:
      - db
    environment:
      # Átadjuk az adatokat a Node.js kódnak
      DB_HOST: db
      DB_USER: appuser
      DB_PASSWORD: apppw
      DB_DATABASE: mozipont_beta
      PORT: 5000
    ports:
      - "5000:5000"           # Backend elérése: http://localhost:5000

volumes:
  db_data: